import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ElectrolizeRegular = localFont({
  src: "./fonts/Electrolize-Regular.ttf",
  variable: "--font-electrolize-regular",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ElectrolizeRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
